### ISSUE TITLE
Using <GlobalStyles />  with Next.js + styled-components outputs external .css file instead of inline css

### ISSUE THREAD

**Issue by berndartmueller** [ben-rogerson/twin.examples#12]
Hey, 

first of all thanks a lot for twin.macro! 

I played around with using twin.macro in Next.js and found out that when using <GlobalStyles /> in `_app.js` and a production build (`next build`), those global styles (especially modern-normalize from `tailwindcss/dist/base.min.css` are extracted into a separate .css file.

As I would like to have all styles inlined in the SSR html response (as that's kind of the idea of css-in-js), is there a way to make that work with Next.js?

Here's the Next.js + styled-components example with a modified `npm run dev` in package.json to produce a production build: https://codesandbox.io/s/frosty-bush-hxl0h

Thanks!

**Comment by ben-rogerson** [comment]
Hey there!
Thanks for bringing up this issue, I've recently had discussions on this topic prior to this and it's been on my mind since.

Currently there's no way to do this with twin, but I'm not opposed to adding a feature flag that enables the functionality you're after.
But just to make sure, can you list the advantages to providing the base styles via SSR?

**Comment by ben-rogerson** [comment]
Hey good news, I'll be actioning this in the next version.

**Comment by ben-rogerson** [comment]
Twin has now dropped the base.min.css file and now pushes all base styles through the GlobalStyles import in [2.0.8](https://github.com/ben-rogerson/twin.macro/releases/tag/2.0.8) 🎉
