### ISSUE TITLE
Twin.macro emotion example flickering when build for production

### ISSUE THREAD

**Issue by armspkt** [ben-rogerson/twin.examples#32]
1. The buggy behavior you’re experiencing and what should be happening instead
I tried this example https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion
but when I build & start (for production) then go to localhost:3000 and refresh page the UI seems flickering.
It does not happen in the development mode.

![2564-02-06 15-43-07 2564-02-06 15_43_20](https://user-images.githubusercontent.com/49720317/107113634-be2bfd80-6892-11eb-93f2-f8c51854ff38.gif)

After some debugging seems like calc css function not call on server-side
![image](https://user-images.githubusercontent.com/49720317/107113665-f7fd0400-6892-11eb-8cf9-2e08c100d111.png)
I guess

  
2. If you're using styled-components, emotion, goober, or something else
emotion

3. A link to a minimal demo showing the bug in action
fork this repo https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion
and use `yarn build && yarn start`

**Comment by ben-rogerson** [comment]
I'll have to look into this futher - perhaps there's something to be learned in [this article](https://emmenko.medium.com/patching-lobotomized-owl-selector-for-emotion-ssr-5a582a3c424c).

**Comment by williamtetlow** [comment]
I found that adding the `CacheProvider` to `_app` fixed the issue

```js
import { CacheProvider } from '@emotion/react'
import { cache } from '@emotion/css'
import { GlobalStyles } from '../components/GlobalStyles'

function MyApp({ Component, pageProps }) {
  return (
    <CacheProvider value={cache}>
      <GlobalStyles />
      <Component {...pageProps} />
    </CacheProvider>
  )
}

export default MyApp
```

**Comment by ben-rogerson** [comment]
@williamtetlow Could you check that your production build is working correctly after adding that? This CacheProvider was originally part of the example until I saw it [caused some issues](https://github.com/ben-rogerson/twin.examples/issues/19).

**Comment by williamtetlow** [comment]
@ben-rogerson so the issue I was seeing was caused by tailwind class using the `first-child` selector and [issue with that selector and emotion SSR.](https://github.com/emotion-js/emotion/issues/1178)

I can't recreate the issue in example repo but implementation in the example repo `_document` is wrong and may be causing confusion.

To overcome issue with `first-child` selector you can use [emotion advanced SSR setup](https://emotion.sh/docs/ssr#advanced-approach) to inline critical css in head instead of colocating `<style>` tags with components in body.

If you don't need to inline CSS in head you shouldn't include custom implementation of `CacheProvider` in `_app` __and__ `CriticalCSS` in `_document`.

We should either update example repo to not have custom implementation in `_document`, update it to use `CacheProvider` in `_app` or have two examples - one with custom SSR and one without.

**Comment by ben-rogerson** [comment]
Hey william, I was wondering which option you would choose here?
#2 caused build issues last time it was part of the example.
